### ISSUE TITLE
Set connection timeout not working properly if the remote server software is down.

### ISSUE THREAD

**Issue by acrolink** [AsyncHttpClient/async-http-client#1025]
The setConnectTimeout setting works perfectly except if the remote server is down, in which case the Async Http Client waits for very long time before returning 408 error. Any idea what mught be causing this? Thanks.

**Comment by slandelle** [comment]
Your reasoning is wrong: you misunderstand connection and request.
If the remote server was indeed down, you wouldn't either be able to connect (if it went down before you tried to connect) or you'd get a connection crash otherwise, which would cause an Exception.
If you got a 408, it means you did receive an HTTP response, meaning your server wasn't down but "just" lagging.

**Comment by acrolink** [comment]
Thanks for clarification. I think I can achieve what I need by setting a boolean false onStart and then set it to true inside onSuccess & onFailure. A postponed method will run after 5 seconds, if boolean still false it would trigger cancel on the asynchttpclient.

**Comment by frewper** [comment]
I am having a similar problem, My Request is neither timing out or the connection timing out when my remote server is down.
@acrolink  which class can I find onStart and onSuccess
