### ISSUE TITLE
Uppercase URIs result in invalid requests (1.8 only)

### ISSUE THREAD

**Issue by gmethvin** [AsyncHttpClient/async-http-client#1111]
It seems like executing a request to a URI such as `HTTP://EXAMPLE.COM/` will try to send the request to port 443 rather than 80, resulting in various kinds of errors. This was originally reported as a Play Framework issue at playframework/playframework#5820.

I created a project demonstrating the issue: https://github.com/gmethvin/asynchttpclient-uppercase

This seems to be fixed in 1.9 but I'm not sure fixing it was intentional. I didn't see any pull requests or issues mentioning the problem.

**Comment by slandelle** [comment]
1.9 was a major rewrite to pave the way for 2.0, so there's a good chance is just cleaned this up without much thought. Is should be just a matter of `equalsIgnoreCase` instead of `equals`.

I personally won't put any effort in maintaining the 1.8 branch. But feel free to provide a fix and I'll gladly ship and release.

**Comment by slandelle** [comment]
Fixed by #1125.

Released as of 1.8.17
