### ISSUE TITLE
[v1.9.31] Default chunk size for client

### ISSUE THREAD

**Issue by ariens** [AsyncHttpClient/async-http-client#1146]
The web server that I'm sending requests to (an OpenTSDB instance)  is configurable to allow chunked requests of a given size.  I was originally observing my AsyncHttpClient requests generating errors because they exceeded the servers's default 8192 byte chunk size.  I thought the default chunk size in [AsyncHttpClient 1.9.31 was 8192](https://github.com/AsyncHttpClient/async-http-client/blob/e418d627107e1e797ea4d03e6b93e2a356ee995e/client/src/main/java/org/asynchttpclient/netty/request/body/BodyChunkedInput.java) as well.  Is that not correct?

**Comment by slandelle** [comment]
First, please use the community mailing list for such questions, not the bug tracker.

Then, no, you're not correct. OpenTSDB setting is about chunked transfer-encoding, and setting a limit on request bodies so that malicious clients can't overflow your server, while AHC setting is about the buffer size before we try to perform an expensive kernel call to flush data over the wire.
