### ISSUE TITLE
Getting java.lang.NoClassDefFoundError: io/netty/handler/ssl/SslContextBuilder

### ISSUE THREAD

**Issue by akstheking** [AsyncHttpClient/async-http-client#1226]
I am receiving below error on using AHC 2.0.11. Is some dependency missing in pom.xml or some dependency I have to add myself.
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/handler/ssl/SslContextBuilder
	at org.asynchttpclient.netty.ssl.DefaultSslEngineFactory.buildSslContext(DefaultSslEngineFactory.java:35)
	at org.asynchttpclient.netty.ssl.DefaultSslEngineFactory.init(DefaultSslEngineFactory.java:56)
	at org.asynchttpclient.netty.channel.ChannelManager.<init>(ChannelManager.java:116)
	at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:81)
```

**Comment by slandelle** [comment]
Please check the pom.xml (our use something like maven to automatically fetch the deps for you).

Then, please use the mailing list for such questions, not the bug tracker.

**Comment by akstheking** [comment]
I am using maven with following dependency in pom.xml : 

```
<dependency>
         <groupId>org.asynchttpclient</groupId>
	<artifactId>async-http-client</artifactId>
	<version>2.0.11</version>
</dependency>
```

Then, it should fetch the dependencies by itself but I guess its not. Is there something else I am missing.

Sorry for posting it here, I will use the mailing list from next time.

**Comment by slandelle** [comment]
It's in `netty-handler` that's automatically fetched along `netty-codec-http`. You probably have a broken download and a corrupted partial file. Clean up your local maven repo and build again.

**Comment by henri-tremblay** [comment]
For the record, I had the same issue. The problem was that the netty version dragged by Gatling was 4.0.44 as expected but the `netty-handler` was 4.0.27 has requested by `cassandra-unit-spring`.

So I think this is a real bug. `gatling-http` should have `netty-handler` has a dependency (transitive or not) to make sure the right version is used.

That said, removing cassandra solve it without adding `netty-handler`. It is now provided by `gatling-recorder`. In the right version of course. I won't look any deeper. It might be a Maven mystery or a Maven property that gets the wrong version and causes the issue.

Bottomline is any encounters it: the solution is: `mvn dependency:tree` and then align you netty dependencies to the same version.

**Comment by slandelle** [comment]
See #1409. Maven nonsense to me: dependencyManagement forces proper netty-handler version inside project modules, but projects depending on AHC wouldn't get it.

**Comment by henri-tremblay** [comment]
Ok. Retrospectively, I vote for Maven nonsense. My comment my help someone one day.

**Comment by slandelle** [comment]
Yeah. Anyway, I'm in the process of releasing new AHC versions with the forced version.

**Comment by slandelle** [comment]
Then, the underlying problem is that Netty is becoming THE way-to-go network framework on the JVM: AHC, Cassandra, Gatling, Play, Spring Boot, Vert.x, Artemis, etc... So classpath clashes are bound to happen...

**Comment by henri-tremblay** [comment]
In fact the real thing here is that I'm using JHipster, so the gatling tests are in the same project has everything else to be compact. To our auditors: I really don't recommend that. Just create a project dedicated to Gatling using the gatling-maven-archetype. This will remove a lot of headaches.
