### ISSUE TITLE
Remotely closed Exception

### ISSUE THREAD

**Issue by Hannes1** [AsyncHttpClient/async-http-client#1360]
Hello,

i got a org.asynchttpclient.exception.RemotelyClosedException: Remotely closed when i try to connect to a domain. The accept any certificate option is enabled.

Example url: https://secure.webres.net

**Comment by slandelle** [comment]
So...

First, about the `RemotelyClosedException`: basically, your server never responds to AHC's ClientHello during TLS handshake, and abruptly closes the connection while it should well behave and respond with an error.

Then, to the actual cause...

Analyzing your website on [ssllabs](https://www.ssllabs.com) gives a rate of C:

<img width="947" alt="ssllabs" src="https://cloud.githubusercontent.com/assets/849197/23141586/c1a5ff4c-f7b7-11e6-87f0-ee9830d5d2cd.png">

The most important thing here is the cipher suites you support:
* TLS_RSA_WITH_RC4_128_MD5: flagged as "INSECURE"
* TLS_RSA_WITH_RC4_128_SHA: flagged as "INSECURE"
* TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)

The first and second one are variant of RC4 that was [cracked in 2001](https://en.wikipedia.org/wiki/Fluhrer,_Mantin_and_Shamir_attack#Background) and support was disabled in Java [since 8u51](http://www.oracle.com/technetwork/java/javase/8u51-relnotes-2587590.html) because it's indeed considered weak.
AFAIK, the third one is not supported in Java.

You can re-enable this cipher suite this way:

```java
Security.setProperty("jdk.tls.disabledAlgorithms", "");
try (AsyncHttpClient client = asyncHttpClient(config()
        .setEnabledCipherSuites(new String[] { "SSL_RSA_WITH_RC4_128_MD5" }))) {
    Response response = client.prepareGet("https://secure.webres.net").execute().get();
    System.err.println(response);
}
```

Still, I would **STRONGLY** recommend against it: your website is *NOT SECURED* and only supports weak cipher suites. I strongly recommend you upgrade to more safe ones. The following ones would work out of the box with AHC:
* TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
* TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
* TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (AES256 requires JCE unlimited strength jurisdiction policy files)
* GCM
* TLS_RSA_WITH_AES_128_GCM_SHA256
* TLS_RSA_WITH_AES_128_CBC_SHA
* TLS_RSA_WITH_AES_256_CBC_SHA (AES256 requires JCE unlimited strength jurisdiction policy files)

**Comment by Hannes1** [comment]
Big Thanks for the fast answer and that detailed explanation, it works!
Actually this is not my website, but i will contact the admins to solve this security issue. 

Have a nice day :)
