### ISSUE TITLE
Connection count leak

### ISSUE THREAD

**Issue by stepancheg** [AsyncHttpClient/async-http-client#1377]
Somewhere in our program we have a connection counter leak.

There are no open connections, but `AsyncHttpClient` throws too many connections exception.

I cannot exactly reproduce the problem, but looking at the code I see at least one issue in function `org.asynchttpclient.netty.request.NettyRequestSender#sendRequestWithNewChannel`:

If `RequestHostnameResolver.INSTANCE.resolve` throws an exception after `acquireChannelLock` (for example, in `asyncHandlerExtensions.onHostnameResolutionAttempt(name)`), then counter is leaked.

**Comment by slandelle** [comment]
> for example, in asyncHandlerExtensions.onHostnameResolutionAttempt(name)

I'm very tempted to document that one is NOT supposed to throw Exceptions in AsyncHandlers and just swallow and log them instead of trying to deal with such mess and report them in the Future/onThrowable...

Anyway, thanks for reporting, but except for the potential problem with `onHostnameResolutionAttempt` and friend, I really can't do anything without a reproducer... Please ping if you manage to create one.

**Comment by stepancheg** [comment]
> I'm very tempted to document that one is NOT supposed to throw Exceptions in AsyncHandlers 

Nobody is safe against stupid errors like `NullPointerException`. But blaming users for throwing unexpected exceptions you make async-http-client library very dangerous to use.

async-http-client should properly handle those exceptions, not document it.
