### ISSUE TITLE
Too many connections error when returning STATE.ABORT

### ISSUE THREAD

**Issue by coud** [AsyncHttpClient/async-http-client#1381]
I just stumbled upon on this today. I set a limit of max connections per host and max connections to 2 and I use AsyncHandler and I tried to abort every onHeadersReceived

`@Override
    public STATE onHeadersReceived(HttpResponseHeaders h) throws Exception {
         return STATE.ABORT;
    }`

After 2 requests it always throws Too many connections error. Looks like it did not free connections when aborting or did I miss something?

**Comment by slandelle** [comment]
Could you please provide the version you're using and a way to reproduce?

**Comment by coud** [comment]
I'm using 2.0.30. About a way to reproduce, please wait. I'll code a very basic sample. I was using also a semaphore to limit calls to prepareGet().execute() with the same limit as my connections limit config and I'm releasing permits in onCompleted method

**Comment by slandelle** [comment]
Long story:
* In 2.0, there was (at least) a bug where connections that weren't offered to the pool (eg when the limit was reached) didn't release the semaphores. I just fixed it: 06c58c6f742fb6d2aa8b468f634aaeddd283a2af.
* In 2.1, the limits have been completely reimplemented, see fix that was shipped in 2.1.0-alpha10: f2408458fa98e5b03835d856aa2870493d26239a. I'm waiting for feedback on the new implementation, and then might backport.
* In 2.0, the behavior is to try to offer connections back to the pool, even in the event of an ABORT.
* In 2.1, ABORT closes the connection.

So, with 2.1, you'd get the result you expect.
But with 2.0, you'd need a margin between your AHC limit and the external semaphore you use because the AHC semaphore might be released AFTER onCompleted (because AHC will wait for the last response chunk before trying to offer to the pool).

**Comment by slandelle** [comment]
@stepancheg Does your application sometimes use handlers that return ABORT?

**Comment by stepancheg** [comment]
No, but our application sometimes throw exception from handlers (e. g. when response is too large).

**Comment by slandelle** [comment]
@stepancheg So, I suspect that's the root cause for you.

**Comment by coud** [comment]
I see, that makes sense. I suspected that there was a race condition. Thank you! I'll try using 2.1
