### ISSUE TITLE
How can i create Request with other UrlEncoding(like GBK), Not UTF-8

### ISSUE THREAD

**Issue by spccold** [AsyncHttpClient/async-http-client#1443]

**Comment by slandelle** [comment]
Please use the mailing list for questions, not the bug tracker.

**Comment by spccold** [comment]
may be i should rewrite the title like below:
~~~
asynchttpclient use utf-8 for url encoding by default, why RequestBuilder don't support customized url encoding?
~~~

**Comment by slandelle** [comment]
URI encoding is specified in [RFC3986](https://tools.ietf.org/html/rfc3986#section-2) and AHC abides to it.
You can't just just whatever encoding you want.

**Comment by EdwardLee03** [comment]
@slandelle I agree with you. If [UriEncoder](https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/util/UriEncoder.java) is defined an interface, not Enum, may would be better. So that customization is also to meet.

**Comment by slandelle** [comment]
Sorry, I don't follow.

Either AHC doesn't behave like it should because it doesn't properly implement a W3C spec, or because it behaves differently from Chrome and FireFox (those guys tend to be one step ahead of specs) and it's a bug that must be fixed.

Or you're trying to build a web application that's not compatible with web standards, and then it's a big "no way".

**Comment by keyhunter** [comment]
@spccold , it is fixed in https://github.com/AsyncHttpClient/async-http-client/issues/1444

**Comment by slandelle** [comment]
Oh my. You were talking about **form** url encoding, not url encoding!!!
