### ISSUE TITLE
setAcceptAnyCertificate(true) doesn't work

### ISSUE THREAD

**Issue by Aiksandr** [AsyncHttpClient/async-http-client#1460]
setAcceptAnyCertificate(true) in config still try to validate certificate and throw exception.

I'm not sure but the problem maybe is here in class `DefaultSslEngineFactory.newSslEngine` row 60
`configureSslEngine(sslEngine, config);`

there using abstract class that can loose acceptAnyCertificate filed (Also i found that parameter config never user there) ->

```java
public abstract class SslEngineFactoryBase implements SslEngineFactory {
    protected void configureSslEngine(SSLEngine sslEngine, AsyncHttpClientConfig config) {
        sslEngine.setUseClientMode(true);
        SSLParameters params = sslEngine.getSSLParameters();
        params.setEndpointIdentificationAlgorithm("HTTPS");
        sslEngine.setSSLParameters(params);
    }
}
```

Bellow is example of config
```java
final DefaultAsyncHttpClientConfig nonProxyConfig = new DefaultAsyncHttpClientConfig.Builder()
                .setAcceptAnyCertificate(true)
                .setFollowRedirect(true)
                .setMaxRedirects(5)
                .setUserAgent(userAgent)
                .setConnectTimeout(10000)
                .setReadTimeout(10000)
                .setRequestTimeout(10000)
                .setMaxConnections(1000)
                .setMaxConnectionsPerHost(1000)
                .build();
        nonProxyAsyncHttpClient = new DefaultAsyncHttpClient(nonProxyConfig);
```

**Comment by slandelle** [comment]
In AHC 2.0, `setAcceptAnyCertificate` is a poor name for what it actually does: setting an insecure TrustManager (that trusts any certificate, like self-signed ones, but fakes ones too, use at your own risks).

With the `SSLEngine`, it's simply not possible to really accept any certificate without losing/disabling other features in the process.

Not setting the endpointIdentificationAlgorithm would not enable any of the SSLEngine HTTPS related features: eg hostname verification but also SNI.
AHC 2.1 drops `setAcceptAnyCertificate` and introduces separate`setDisableHttpsEndpointIdentificationAlgorithm` and `setUseInsecureTrustManager` options.

I suspect you're trying to disable hostname verification, which I would not recommend (but that's your call). Usually, people want to do this because they are using their prod certs for their QA and dev platforms too, instead of using self signed certs there...

AHC 2.1 is drawing near, so I'd recommend upgrading if possible. Otherwise, pass your own SslEngineFactory and override configureSslEngine
