### ISSUE TITLE
Selectively disable SNI

### ISSUE THREAD

**Issue by bramlefebvre** [AsyncHttpClient/async-http-client#1477]
Hi,

I am using the NettyAsyncHttpProvider of async-http-client 1.9.40.
I am getting an exception because the hostname of the http server does not match with the subject CN of the ssl certificate.
I am using AsyncHttpClientConfig.Builder#setHostnameVerifier to set a hostname verifier that always returns true, but that doesn't work.
Is it possible to disable SNI for one connection and enable it for another connection at the same time? 

Thanks in advance.

**Comment by slandelle** [comment]
> I am using the NettyAsyncHttpProvider of async-http-client 1.9.40.

Then, please upgrade, AHC1 has reached end of life for more than one year.

> I am getting an exception because the hostname of the http server does not match with the subject CN of the ssl certificate.

Which is pretty bad. As a user, this would mean this website mustn't be trusted. Quite often, people end up in this situation because they want to reuse their prod cert in QA env instead of using a self signed certificate.

> I am using AsyncHttpClientConfig.Builder#setHostnameVerifier to set a hostname verifier that always returns true, but that doesn't work.

AHC 1 supported multiple backends, including an UrlConnection based one. Only this one really supported setting a HostnameVerifier, as this is only supported by HttpUrlConnection and not by SSLEngine. It can't work with Netty.

With AHC2, you can disable enabling HTTPS algorithm on the SSLEngine. That would disable hostname verification (don't do that on prod) but will also disable SNI.

> Is it possible to disable SNI for one connection and enable it for another connection at the same time?

Hostname verification has nothing to do with SNI.

Now, this is a bugtracker, hence for bugs. For questions, please use the mailing list.
