### ISSUE TITLE
CONNECT request is sent with default AHC user-agent, not with the on from RequestBuilder

### ISSUE THREAD

**Issue by insticore** [AsyncHttpClient/async-http-client#1730]
The new CONNECT request is made by NettyRequestFactory, where User-Agent is set from AsyncHttpClientConfig, if I correctly understand.
So in result the user-agent differs from the following requests.

Please, is it possible to fix?

This is captured by Wireshark, the first request CONNECT and the headers are:
**accept: */*.
user-agent: AHC/2.1**

**Comment by slandelle** [comment]
I no longer maintain this project (actually looking for new maintainers).
Contributing a fix would be very much welcomed.

**Comment by TomGranot** [comment]
@insticore Just pinging again to see whether you can clarify a bit more. No rush:)

**Comment by insticore** [comment]
@TomGranot hi there, thanks a lot for keeping this great project alive!
The issue here is that I need to use some specific user agent for each request by adding it as an 'User-Agent' header like here
`Dsl.get(<url>).addHeader("user-agent", <custom UA>)`.
But when I use HTTPS connection, there are two HTTP requests sent, the first one is a _CONNECT_ with user-agent not from RequestBuilder, but the one from AsyncHttpClientConfig (AHC/2.1 by default). And only for the second request (_GET_ one) my custom user-agent is set correctly.

**Comment by TomGranot** [comment]
@insticore today's a rough one, but will take a look tomorrow evening. If you could ping me if i forget that would be great;)

**Comment by insticore** [comment]
@TomGranot hello, just asking if there any news for this issue
And also found a screenshot I did for a request with incorrect user-agent
![image](https://user-images.githubusercontent.com/6097207/97840387-9144d900-1cec-11eb-95dc-fab6e31f4128.png).
So here is the first CONNECT request with default "AHC/2.1", and the next requests have custom user-agent I set within the code.

**Comment by TomGranot** [comment]
@insticore I think I understand better now. Looking.

**Comment by TomGranot** [comment]
@insticore Just to clarify for anybody reading this at a later point in time - this does not affect you if you don't have a proxy server in the way. In @insticore's case there's an [SSL proxy](https://avinetworks.com/glossary/ssl-proxy/) that's sitting between them and the internet, causing the normal flow of HTTPS to be a bit different. Instead of:

1. HTTPS request to original host

We now have:

1. HTTP request to proxy
2. HTTPS requests from proxy to original host

What @insticore is saying is that in request no. 1 he's seeing the wrong agent. This *is not* related to AsyncHttpClient's proxy (an [example here](https://github.com/AsyncHttpClient/async-http-client#configuration)) but instead has more to do with the network topology @insticore have in front of them (if I understand correctly).

Back to the original question (editing):

**Comment by TomGranot** [comment]
@insticore Merged into master, will be released in 2.12.3.
