### ISSUE TITLE
java.io.IOException: Invalid Status code=200 text=OK

### ISSUE THREAD

**Issue by supertick** [AsyncHttpClient/async-http-client#1840]
Hello !
I'm attempting to setup a websocket with AsyncHttpClient similar to how its setup here - https://www.baeldung.com/async-http-client-websockets 

But I always get the same error and closing of the socket.
```java.io.IOException: Invalid Status code=200 text=OK```
Any ideas of what I might try ?
I know the websocket server is working ... I tested it with a browser plugin and I can see the messages streaming
![image](https://user-images.githubusercontent.com/1266144/210248680-7ae0be7b-6fa8-4f79-87cb-5c631ba32ee7.png)

**Comment by hyperxpro** [comment]
Can you show stack trace?

**Comment by slandelle** [comment]
No need for a stacktrace.

> java.io.IOException: Invalid Status code=200 text=OK

This error is very clear (at least to me): your server replied to the HTTP request opening the WebSocket with a `200 OK` status, which is **invalid for a WebSocket**. It should be `101 Switching Protocols`.

My best guess is that your url is incorrect, eg using the `http` scheme instead of the `ws` one, or not providing the expected parameters and being redirected.

**Comment by hyperxpro** [comment]
As @slandelle mentioned.
