### ISSUE TITLE
Netty: NTLM utterly broken

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#730]
- Handshake should only happen when performing the first request on a connection
- On preemptive auth, step 1 is performed twice
- A "NTLM " string is prepended to the NTLM Domain when computing the Type1 message
- Connection is not reused, which violates NTLM logic and causes Type1 message so be re-issued while sending the Type3 one.

**Comment by jroper** [comment]
Hi @slandelle, I found this issue after noticing the NTLM prefixed onto the domain, not the header, in 1.8.x, and was going to submit a pull request to fix that, but it sounds like from this issue that that's not the only problem with NTLM.  It seems like backporting this to 1.8.x would not be trivial, but I may end up doing that because this is for a customer of ours.  If I do backport it, would you be interested in accepting the fix?  If not, it's no big deal, we can just do a private release for our customer.

**Comment by slandelle** [comment]
@jroper No problem with releasing some new 1.8.x, as long as there's no API breakage.

Beware, there's other related commits: 83d5db04e345e2f12d9940683c5dbdb9cb70eb58, acdb7e4ded0a0e957a3f6d01689a21f7e4246bf2, 3425a303c9ef26012ad72b89d7d3624ae20cb8f8, fe8215b904728eea9693c28dcfc992af7e201b26, 43bfdb2b733d64c5c36f739a9e5d1659d7e4091d, 5a1a2cec0560b039061889ef7f8f6af5e40c7038

Sorry for the commit mess, it was really difficult for me to get it right without having access to a NTLM domain...
