### ISSUE TITLE
async http client does connect to some HTTPS pages with valid certificates

### ISSUE THREAD

**Issue by schleichardt** [AsyncHttpClient/async-http-client#925]
test code: https://github.com/schleichardt/async-http-client-bug-with-ssl/blob/master/src/test/java/ClientTest.java
(doesNotConnectToHttps test fails)

repo: https://github.com/schleichardt/async-http-client-bug-with-ssl

stacktrace: https://travis-ci.org/schleichardt/async-http-client-bug-with-ssl/jobs/68301648#L634

**Comment by slandelle** [comment]
"Teach a man how to fish" mode:
1. Run with "-Djavax.net.debug=all"
2. Have a look at [JSSE troubleshooting doc](http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#InstallProbs). At this point, "WTF" can be appropriate.
3. Configure AHC accordingly (see AsyncHttpClientConfig)

**Comment by wsargent** [comment]
Also, check out the bug report: http://noverse.com/blog/2012/06/how-to-write-a-good-bug-report/

A test failure because the build machine cannot connect could be many things -- most probably, it's because of network congestion or the site being down.

**Comment by slandelle** [comment]
Well, the way the issue was reported here was fine by me. It's so rare to get a reproducer!

Regarding my answer, I just thought @schleichardt would benefit more of searching by himself with a few hints, than me just giving the answer.

AHC doesn't do anything fancy and uses plain JSSE facilities (but some features are disabled when running "acceptAll"). So when facing a JSSE related problem, just debug the standard way: enable debug logging and check the handshake.
