### ISSUE TITLE
works well with proxy tools(example charles) but normal WIFI environment

### ISSUE THREAD

**Issue by johnshazhu** [AsyncHttpClient/async-http-client#971]
WIFI Environment:
    If i do not use proxy tools, it always occurs connection timeout exception.Otherwise it works well.

**Comment by slandelle** [comment]
No idea what you're talking about.

**Comment by johnshazhu** [comment]
I'm sorry, my English is not very good and maybe didn't describe the problem clearly。
Our app have two platform versions : android & ios, and the android version use this library as the network framework.
In same wifi network condition,  when send request to sever, ios always gets the response immediately, but android client always gets ConnectTimeoutException after default wait time(30 seconds).
But when i use charles and set phone's network proxy (proxy IP address is local PC's IP address),
the android client also works well and no timeout exception occurs.
Is there some difference between normal network and the network with proxy?

**Comment by slandelle** [comment]
First, are you sure you're using this library and not [loop4j]((https://github.com/loopj/android-async-http)? Frequently, Android devs get confused and post here instead of there. Explanations [here](https://github.com/loopj/android-async-http/issues/876).

Then, proxy API is a bit weird, and you currently have to tell if the proxy is for HTTP and HTTPS in the `ProxyServer` constructor. Maybe you're passing a proxy for HTTP (default)  and using is over HTTPS.

Finally, if you indeed use AHC and not loop4j, please use our google group for questions.
