### ISSUE TITLE
FluentCaseInsensitiveStringsMap keyLookup un-sync with values after iterator remove

### ISSUE THREAD

**Issue by ben-tsai** [AsyncHttpClient/async-http-client#976]
After using FluentCaseInsensitiveStringsMap.entrySet().iterator() to remove entries from map, keyLookup map loses sync with values map.

To reproduce:

```java
FluentCaseInsensitiveStringsMap map = new FluentCaseInsensitiveStringsMap();
map.add("a", "AAA");
map.add("b", "BBB");
map.add("c", "CCC");

for (Iterator<Map.Entry<String, List<String>>> iter = map.entrySet().iterator(); iter.hasNext(); ) {
    if (iter.next().getKey().equalsIgnoreCase("a")) {
        iter.remove();
    }
}

System.out.println("map.toString(): " + map.toString());
System.out.println("map.keySet().toString(): " + map.keySet().toString());
System.out.println("map.containsKey(\"a\"): " + map.containsKey("a"));
System.out.println("map.get(\"a\"): " + map.get("a"));
System.out.println("map.get(\"b\"): " + map.get("b"));
System.out.println("map.get(\"xxx\"): " + map.get("xxx"));
```

Output:

```
map.toString(): "b=BBB"; "c=CCC"
map.keySet().toString(): [a, b, c]         // expected [b, c]
map.containsKey("a"): true                 // expected false
map.get("a"): null                         // expected empty set 
map.get("b"): [BBB]
map.get("xxx"): []                         // just to show what is returned when key doesn't exist
```

Thanks
Ben

**Comment by ben-tsai** [comment]
Hi, 

Please review proposed fix, thanks: https://github.com/AsyncHttpClient/async-http-client/pull/977

Ben

**Comment by slandelle** [comment]
Hi Ben,

Thanks for reporting and proposing a fix.

Actually, I don't think `FluentCaseInsensitiveStringsMap` was originally designed so that you remove entries with the `Iterator` (which is, BTW, something `Iterator` design is very criticized for: removing entries has nothing to do with the responsibility of iterating).
What I mean is that `FluentCaseInsensitiveStringsMap#iterator()` returns an Iterator on a read-only view.

IMO, we should align `iterator()`, `keySet()` and `entrySet()` behaviors:
* either go with read-only views everywhere
* or go with mutable Iterators everywhere

My favorite choice would be the former. @jfarcand WDYT?

Then, regarding your proposed fix (#977), I wonder if resync shouldn't happen in `Iterator.remove()` instead.

**Comment by ben-tsai** [comment]
Hi Stephane,

Thanks for the explanation :beers:.

I current use a request filter in my project to remove headers that matches certain conditions.  Having a mutable iterator is IMHO more efficient / convenient.  However, since there are many other ways to remove those headers, I'll respect whichever final decision you and @jfarcand decide on.

As for https://github.com/AsyncHttpClient/async-http-client/pull/977, updating keyLookup in Iterator.remove() would definitely be better if we're willing to spend more effort here.  The proposed solution is kind of just a quick fix.

Thanks.

**Comment by slandelle** [comment]
ping @jfarcand

**Comment by jfarcand** [comment]
@ben-tsai @slandelle I agree with Stéphane, we should do `either go with read-only views everywhere`.

**Comment by ben-tsai** [comment]
Hi @slandelle  @jfarcand, in that case lets align the behaviors? Thanks

**Comment by slandelle** [comment]
Actually, I think we're going to drop `FluentCaseInsensitiveStringsMap`, see #987.
